name: urbano106
description: Urbano 106 FM - Radio App
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46
  webview_flutter: ^4.4.2
  http: ^1.1.0
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  video_player: ^2.8.3
  chewie: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/WhatsApp.svg
